version: '3'
services:
  zookeeper:
    image: manukoli1986/zookeeper:v1
    environment:
     - "advertised.listeners:localhost"
    ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"
     - "5000:5000"

  kafka:
    image: manukoli1986/kafkacluster:v3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
#    links:
#      - "zookeeper:zookeeper"
    volumes:
      - "./conf:/opt/kafka/config"
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - "./data:/data"

  aerospike:
    image: aerospike/aerospike-server
    environment:
      - "NAMESPACE=payments"
      - "MEM_GB=5"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
