apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkacluster
  labels:
    name: kafkacluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafkacluster
  template:
    metadata:
      labels:
        name: kafkacluster
    spec:
      containers:
      - name: kafka
        image: manukoli1986/kafkacluster:v3
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: kafka-config
          mountPath: /opt/kafka/config
      - name: zookeeper
        image: manukoli1986/zookeeper:v1
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        - containerPort: 5000
      volumes:
        - name: kafka-config
          configMap:
            name: kafka-config
---
apiVersion: v1 
kind: Service 
metadata: 
  name: kafkacluster
  labels:
    name: kafkacluster
spec: 
  ports: 
  - port: 9092 
    targetPort: 9092 
    name: kafka-port
  - port: 2181 
    targetPort: 2181 
    name: zookeeper-port
  selector: 
    name: kafkacluster 
  type: LoadBalancer 
