apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkacluster
  labels:
    name: kafkacluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafkacluster
  template:
    metadata:
      labels:
        name: kafkacluster
    spec:
      containers:
      - name: kafka
        image:kafkacluster:v3
        ports:
        - containerPort: 9092

      - name: zookeeper
        image: manukoli1986/zookeeper:v1
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        - containerPort: 5000
---
apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: kafkaApp 
  name: kafka 
spec: 
  ports: 
  - port: 9092 
    targetPort: 9092 
  - port: 2181 
    targetPort: 2181 
  selector: 
    app: kafkaApp 
  type: LoadBalancer 
